name: 'setup-rust'
description: 'install Rust toolchain, using rustup'
# Adapted from https://github.com/actions-rs/toolchain/issues/216#issuecomment-1291613319

inputs:
  toolchain:
    required: false
    description: "Rust toolchain, e.g. 'stable' or 'nightly'"
    default: stable
  target:
    required: false
    description: "Comma-separated string of the targets to install e.g. 'aarch64-apple-darwin, x86_64-pc-windows-msvc'"
  components:
    required: false
    description: "Comma-separated string of additional components to install e.g. 'clippy, rustfmt'"


runs:
  using: "composite"
  steps:
    - name: "Install Rust toolchain"
      run: |
        components=$(for c in ${components//,/ }; do echo -n ' --component' $c; done)
        targets=$(for t in ${targets//,/ }; do echo -n ' --target' $t; done)
        
        rustup toolchain install ${{ inputs.toolchain }} $targets $components --profile minimal --no-self-update
        rustup default ${{ inputs.toolchain }}
      env:
        components: ${{ inputs.components }}
        targets: ${{ inputs.targets }}
      shell: bash

    - name: "Set environment variables used by toolchain"
      run: |
        echo CARGO_TERM_COLOR=always >> $GITHUB_ENV
        echo CARGO_INCREMENTAL=0 >> $GITHUB_ENV
        echo RUST_BACKTRACE=1 >> $GITHUB_ENV

        rustc --version --verbose
      shell: bash
