[workspace]
members = [".", "dispel-gui", "dispel-macros", "gui-widgets", "hexedit"]
resolver = "2"

[workspace.dependencies]
iced = { git = "https://github.com/dimspell/iced", default-features = false, rev = "8c028a7fb5b376c5a0539834a4bcde9eca6ee874" }
iced_test = { git = "https://github.com/dimspell/iced", rev = "8c028a7fb5b376c5a0539834a4bcde9eca6ee874" }

[workspace.metadata]
features = ["iced_test"]

[patch.crates-io]
winit = { git = "https://github.com/iced-rs/winit.git", rev = "05b8ff17a06562f0a10bb46e6eaacbe2a95cb5ed" }

[lib]
name = "dispel_core"
path = "src/lib.rs"

[package]
name = "dispel-extractor"
version = "0.8.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
image = "0.24.7"
encoding_rs = "0.8.33"
encoding_rs_io = "0.1.7"
clap = { version = "4.4.10", features = ["derive"] }
serde_json = { version = "1.0", features = [] }
serde = { version = "1.0", features = ["derive"] }
dispel-macros = { path = "dispel-macros" }
csv = "1.3"
qbsdiff = "1.4"
uuid = { version = "1", features = ["v4", "serde"] }
zip = "8"
thiserror = "2"

[dependencies.rusqlite]
version = "0.39.0"
features = ["bundled"]

[profile.dev.package.cosmic-text]
overflow-checks = false

[dev-dependencies]
proptest = "1.4"
tempfile = "3.8"
