CREATE TABLE IF NOT EXISTS monsters
(
    id                      INTEGER PRIMARY KEY,
    name                    TEXT,
    health_points_max       INTEGER,
    health_points_min       INTEGER,
    magic_points_max        INTEGER,
    magic_points_min        INTEGER,
    walk_speed              INTEGER,
    to_hit_max              INTEGER,
    to_hit_min              INTEGER,
    to_dodge_max            INTEGER,
    to_dodge_min            INTEGER,
    offense_max             INTEGER,
    offense_min             INTEGER,
    defense_max             INTEGER,
    defense_min             INTEGER,
    magic_attack_max        INTEGER,
    magic_attack_min        INTEGER,
    is_undead               INTEGER,
    has_blood               INTEGER,
    ai_type                 INTEGER,
    exp_gain_max            INTEGER,
    exp_gain_min            INTEGER,
    gold_drop_max           INTEGER,
    gold_drop_min           INTEGER,
    detection_sight_size    INTEGER,
    distance_range_size     INTEGER,
    known_spell_slot1       INTEGER,
    known_spell_slot2       INTEGER,
    known_spell_slot3       INTEGER,
    is_oversize             INTEGER,
    magic_level             INTEGER,
    special_attack          INTEGER,
    special_attack_chance   INTEGER,
    special_attack_duration INTEGER,
    boldness                INTEGER,
    attack_speed            INTEGER
);