CREATE TABLE IF NOT EXISTS magic_spells (
    id INTEGER PRIMARY KEY,
    enabled BOOLEAN NOT NULL,
    effect_visual_blends_with_background INTEGER,
    base_damage INTEGER,
    base_success_rate INTEGER,
    mana_cost INTEGER,
    reserved_0x14 INTEGER,
    reserved_0x18 INTEGER,
    effect_animation_repeats INTEGER,
    range INTEGER,
    reserved_0x24 INTEGER,
    cast_duration INTEGER,
    unused_constant_one INTEGER,
    effect_value INTEGER,
    effect_type INTEGER,
    effect_modifier INTEGER,
    reserved_0x3c INTEGER,
    magic_school INTEGER,
    target_animation_blends_with_background INTEGER,
    animation_set_id INTEGER,
    effect_visual_id INTEGER,
    icon_id INTEGER,
    targeting_mode INTEGER
);
