CREATE TABLE IF NOT EXISTS weapons
(
    id            INTEGER,
    name          TEXT,
    description   TEXT,
    base_price    INTEGER,
    weapon_item_id INTEGER,
    health_points INTEGER,
    mana_points  INTEGER,
    strength      INTEGER,
    agility       INTEGER,
    wisdom        INTEGER,
    constitution            INTEGER,
    to_dodge           INTEGER,
    to_hit           INTEGER,
    attack        INTEGER,
    defense       INTEGER,
    magical_strength           INTEGER,
    durability    INTEGER,
    reserved_0x108 INTEGER,
    reserved_0x10a INTEGER,
    req_strength  INTEGER,
    reserved_0x10e INTEGER,
    req_agility        INTEGER,
    reserved_0x112 INTEGER,
    req_wisdom    INTEGER,
    reserved_0x116 INTEGER,
    reserved_0x118 INTEGER,
    reserved_0x11a INTEGER
)
