CREATE TABLE IF NOT EXISTS ch_datas (
    unused_name TEXT NOT NULL,
    warrior_strength INTEGER,
    warrior_constitution INTEGER,
    warrior_wisdom INTEGER,
    warrior_agility INTEGER,
    knight_strength INTEGER,
    knight_constitution INTEGER,
    knight_wisdom INTEGER,
    knight_agility INTEGER,
    archer_strength INTEGER,
    archer_constitution INTEGER,
    archer_wisdom INTEGER,
    archer_agility INTEGER,
    mage_strength INTEGER,
    mage_constitution INTEGER,
    mage_wisdom INTEGER,
    mage_agility INTEGER,
    reserved_stat INTEGER,
    warrior_offense_bonus INTEGER,
    knight_defense_bonus INTEGER,
    archer_dodge_bonus INTEGER,
    archer_hit_bonus INTEGER,
    mage_magic_power_bonus INTEGER
);
