CREATE TABLE npc_refs
(
    file_id                 INTEGER NOT NULL REFERENCES npc_ref_files(id),
    row_id                  INTEGER,
    file_record_id          INTEGER,
    npc_ini_id              INTEGER REFERENCES npc_inis(id) ON DELETE SET NULL,
    name                    TEXT,
    role_description        TEXT,
    party_member_slot       INTEGER,
    show_on_event           INTEGER REFERENCES events(event_id) ON DELETE SET NULL,
    movement_mode           INTEGER,
    goto1_filled            INTEGER,
    goto2_filled            INTEGER,
    goto3_filled            INTEGER,
    goto4_filled            INTEGER,
    goto1_x                 INTEGER,
    goto2_x                 INTEGER,
    goto3_x                 INTEGER,
    goto4_x                 INTEGER,
    goto1_y                 INTEGER,
    goto2_y                 INTEGER,
    goto3_y                 INTEGER,
    goto4_y                 INTEGER,
    unknown_2               INTEGER,
    unknown_3               INTEGER,
    unknown_4               INTEGER,
    unknown_5               INTEGER,
    looking_direction       INTEGER,
    unknown_6               INTEGER,
    unknown_7               INTEGER,
    unknown_8               INTEGER,
    unknown_9               INTEGER,
    unknown_10              INTEGER,
    unknown_11              INTEGER,
    unknown_12              INTEGER,
    unknown_13              INTEGER,
    unknown_14              INTEGER,
    unknown_15              INTEGER,
    unknown_16              INTEGER,
    interaction_mode        INTEGER,
    interaction_result_item_id   INTEGER,
    interaction_result_item_type INTEGER,
    interaction_result_raw  INTEGER,
    interaction_range_offset INTEGER,
    dialog_file_id          INTEGER NOT NULL REFERENCES dialogue_script_files(id),
    dialog_id               INTEGER,
    dialogue_face_sprite_id INTEGER,
    FOREIGN KEY (dialog_file_id, dialog_id) REFERENCES dialogue_scripts(dialog_file_id, id)
);
