CREATE TABLE npc_refs
(
    file_id                 INTEGER NOT NULL,
    id                      INTEGER,
    file_record_id          INTEGER,
    npc_ini_id              INTEGER,
    name                    TEXT,
    role_description        TEXT,
    role_result             INTEGER,
    show_on_event           INTEGER,
    movement_mode           INTEGER,
    goto1_filled            INTEGER,
    goto2_filled            INTEGER,
    goto3_filled            INTEGER,
    goto4_filled            INTEGER,
    goto1_x                 INTEGER,
    goto2_x                 INTEGER,
    goto3_x                 INTEGER,
    goto4_x                 INTEGER,
    goto1_y                 INTEGER,
    goto2_y                 INTEGER,
    goto3_y                 INTEGER,
    goto4_y                 INTEGER,
    waypoint1_wait_time               INTEGER,
    waypoint2_wait_time               INTEGER,
    waypoint3_wait_time               INTEGER,
    waypoint4_wait_time               INTEGER,
    waypoint1_facing_direction       INTEGER,
    waypoint2_facing_direction               INTEGER,
    waypoint3_facing_direction               INTEGER,
    waypoint4_facing_direction               INTEGER,
    waypoint1_reserved               INTEGER,
    waypoint2_reserved              INTEGER,
    waypoint3_reserved              INTEGER,
    waypoint4_reserved              INTEGER,
    activation_rect_x1              INTEGER,
    activation_rect_y1              INTEGER,
    activation_rect_x2              INTEGER,
    activation_rect_y2              INTEGER,
    interaction_mode        INTEGER,
    interaction_result_item_id   INTEGER,
    interaction_result_item_type INTEGER,
    interaction_result_parameter  INTEGER,
    interaction_range_offset INTEGER,
    dialog_file_id          INTEGER NOT NULL,
    dialog_id               INTEGER,
    dialogue_face_sprite_id INTEGER
);
