CREATE TABLE IF NOT EXISTS extra_refs
(
    file_id   INTEGER NOT NULL REFERENCES extra_ref_files(id),
    id                       INTEGER,
    number_in_file           INTEGER,
    ext_id                   INTEGER REFERENCES extras(id) ON DELETE SET NULL,
    name                     TEXT,
    object_type              INTEGER,
    x_pos                    INTEGER,
    y_pos                    INTEGER,
    rotation                 INTEGER,
    unknown2                 BLOB,
    unknown3                 INTEGER,
    closed                   INTEGER,
    required_item_id         INTEGER,
    required_item_type_id    INTEGER,
    required_item_raw        INTEGER,
    unknown4                 INTEGER,
    required_item_id2        INTEGER,
    required_item_type_id2   INTEGER,
    required_item2_raw       INTEGER,
    unknown6                 INTEGER,
    unknown7                 INTEGER,
    unknown8                 INTEGER,
    unknown9                 INTEGER,
    gold_amount              INTEGER,
    item_id                  INTEGER,
    item_type_id             INTEGER,
    item_raw                 INTEGER,
    unknown10                INTEGER,
    item_count               INTEGER,
    unknown11                INTEGER,
    unknown12                INTEGER,
    unknown13                INTEGER,
    unknown14                BLOB,
    event_id                 INTEGER REFERENCES events(event_id) ON DELETE SET NULL,
    message_id               INTEGER REFERENCES messages(id) ON DELETE SET NULL,
    unknown15                INTEGER,
    unknown16                INTEGER,
    unknown17                INTEGER,
    interactive_element_type INTEGER,
    unknown18                BLOB,
    is_quest_element         INTEGER,
    unknown20                INTEGER,
    unknown21                INTEGER,
    unknown22                INTEGER,
    unknown23                INTEGER,
    visibility               INTEGER,
    unknown24                INTEGER,
    unknown25                INTEGER,
    unknown26                INTEGER,
    unknown27                INTEGER
);