CREATE TABLE monster_refs
(
    file_id         INTEGER NOT NULL,
    id              INTEGER,
    placement_id    INTEGER,
    monster_db_id   INTEGER,
    map_x           INTEGER,
    map_y           INTEGER,
    initial_patrol_countdown INTEGER,
    skip_ai_action  INTEGER,
    initial_active_flag INTEGER,
    ai_type_override INTEGER,
    event_id_on_kill INTEGER,
    loot1_item_id   INTEGER,
    loot1_item_type INTEGER,
    loot1_item_raw  INTEGER,
    loot2_item_id   INTEGER,
    loot2_item_type INTEGER,
    loot2_item_raw  INTEGER,
    loot3_item_id   INTEGER,
    loot3_item_type INTEGER,
    loot3_item_raw  INTEGER,
    drop_all_loot   INTEGER,
    force_ai_update INTEGER
);
