CREATE TABLE IF NOT EXISTS magic_spells (
    id INTEGER PRIMARY KEY,
    enabled BOOLEAN NOT NULL,
    flag1 INTEGER,
    mana_cost INTEGER,
    success_rate INTEGER,
    base_damage INTEGER,
    reserved1 INTEGER,
    reserved2 INTEGER,
    flag2 INTEGER,
    range INTEGER,
    reserved3 INTEGER,
    level_required INTEGER,
    constant1 INTEGER,
    effect_value INTEGER,
    effect_type INTEGER,
    effect_modifier INTEGER,
    reserved4 INTEGER,
    magic_school INTEGER,
    flag3 INTEGER,
    animation_id INTEGER,
    visual_id INTEGER,
    icon_id INTEGER,
    target_type INTEGER
);
