CREATE TABLE monster_refs
(
    file_id         INTEGER NOT NULL REFERENCES monster_ref_files(id),
    id              INTEGER,
    file_id         INTEGER,
    mon_id          INTEGER REFERENCES monster_inis(id) ON DELETE SET NULL,
    pos_x           INTEGER,
    pos_y           INTEGER,
    padding1        INTEGER,
    padding2        INTEGER,
    padding3        INTEGER,
    padding4        INTEGER,
    event_id        INTEGER,
    loot1_item_id   INTEGER,
    loot1_item_type INTEGER,
    padding6        INTEGER,
    padding7        INTEGER,
    loot2_item_id   INTEGER,
    loot2_item_type INTEGER,
    padding8        INTEGER,
    padding9        INTEGER,
    loot3_item_id   INTEGER,
    loot3_item_type INTEGER,
    padding10       INTEGER,
    padding11       INTEGER,
    padding12       INTEGER,
    padding13       INTEGER
);
