CREATE TABLE monster_refs
(
    file_id         INTEGER NOT NULL,
    id              INTEGER,
    placement_id    INTEGER,
    monster_db_id   INTEGER,
    map_x           INTEGER,
    map_y           INTEGER,
    initial_patrol_countdown INTEGER,
    skip_ai_action  INTEGER,
    initial_active_flag INTEGER,
    ai_type_override INTEGER,
    event_id_on_kill INTEGER,
    loot_item_1_id   INTEGER,
    loot_item_1_type INTEGER,
    loot_item_1_raw  INTEGER,
    loot_item_2_id   INTEGER,
    loot_item_2_type INTEGER,
    loot_item_2_raw  INTEGER,
    loot_item_3_id   INTEGER,
    loot_item_3_type INTEGER,
    loot_item_3_raw  INTEGER,
    drop_all_loot   INTEGER,
    force_ai_update INTEGER
);
