INSERT OR REPLACE INTO ch_datas (
    unused_name,
    warrior_strength,
    warrior_constitution,
    warrior_wisdom,
    warrior_agility,
    knight_strength,
    knight_constitution,
    knight_wisdom,
    knight_agility,
    archer_strength,
    archer_constitution,
    archer_wisdom,
    archer_agility,
    mage_strength,
    mage_constitution,
    mage_wisdom,
    mage_agility,
    reserved_stat,
    warrior_offense_bonus,
    knight_defense_bonus,
    archer_dodge_bonus,
    archer_hit_bonus,
    mage_magic_power_bonus
) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, ?22, ?23);
