INSERT OR REPLACE INTO heal_items(id,
                       name,
                       description,
                       base_price,
                       pz,
                       pm,
                       full_pz,
                       full_pm,
                       poison_heal,
                       petrif_heal,
                       polimorph_heal)
VALUES (?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        ?8,
        ?9,
        ?10,
        ?11)