INSERT INTO magic_spells (
    id,
    enabled,
    effect_visual_blends_with_background,
    base_damage,
    base_success_rate,
    mana_cost,
    reserved_0x14,
    reserved_0x18,
    effect_animation_repeats,
    range,
    reserved_0x24,
    cast_duration,
    animation_data_index,
    effect_value,
    effect_type,
    effect_modifier,
    reserved_0x3c,
    magic_school,
    target_animation_blends_with_background,
    animation_set_id,
    effect_visual_id,
    icon_id,
    targeting_mode
) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, ?22, ?23);
