INSERT OR REPLACE INTO heal_items(id,
                       name,
                       description,
                       base_price,
                       runtime_item_index_slot,
                       health_points,
                       mana_points,
                       restores_full_health,
                       restores_full_mana,
                       cures_poison,
                       cures_petrification,
                       cures_polymorph,
                       reserved_trailer)
VALUES (?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        ?8,
        ?9,
        ?10,
        ?11,
        ?12,
        ?13)
