INSERT INTO magic_spells (
    id,
    enabled,
    flag1,
    mana_cost,
    success_rate,
    base_damage,
    reserved1,
    reserved2,
    flag2,
    range,
    reserved3,
    level_required,
    constant1,
    effect_value,
    effect_type,
    effect_modifier,
    reserved4,
    magic_school,
    flag3,
    animation_id,
    visual_id,
    icon_id,
    target_type
) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, ?22, ?23);
