INSERT OR REPLACE INTO monster_refs(file_id,
                          id,
                          placement_id,
                         monster_db_id,
                         map_x,
                         map_y,
                         initial_patrol_countdown,
                         skip_ai_action,
                         initial_active_flag,
                         ai_type_override,
                         event_id_on_kill,
                         loot1_item_id,
                         loot1_item_type,
                         loot1_item_raw,
                         loot2_item_id,
                         loot2_item_type,
                         loot2_item_raw,
                         loot3_item_id,
                         loot3_item_type,
                         loot3_item_raw,
                         drop_all_loot,
                         force_ai_update)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, ?22);
