INSERT OR REPLACE INTO monster_refs(file_path,
                         id,
                         file_id,
                         mon_id,
                         pos_x,
                         pos_y,
                         padding1,
                         padding2,
                         padding3,
                         padding4,
                         padding5,
                         loot1_item_id,
                         loot1_item_type,
                         padding6,
                         padding7,
                         loot2_item_id,
                         loot2_item_type,
                         padding8,
                         padding9,
                         loot3_item_id,
                         loot3_item_type,
                         padding10,
                         padding11,
                         padding12,
                         padding13)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, ?22, ?23, ?24, ?25);
