#[derive(Debug, Clone)]
pub enum ViewerMessage {
    DbPathChanged(String),
    BrowseDb,
    Connect,
    TablesLoaded(Result<Vec<String>, String>),
    SelectTable(String),
    DataLoaded(Result<crate::db::QueryResult, String>),
    Search(String),
    SortColumn(usize),
    NextPage,
    PrevPage,
    CellClick(usize, usize),
    CellEdit(String),
    CellConfirm,
    CellCancel,
    Commit,
    CommitDone(Result<usize, String>),
    ToggleSql,
    SqlChanged(String),
    RunSql,
    ExportCsv,
    CsvSaved(Result<String, String>),
    RevertEdits,
}
