//! Concrete [`RecordPatcher`](super::patcher::RecordPatcher) implementations,
//! one per catalog file format.
//!
//! Most patchers are auto-generated by `#[derive(RecordPatcher)]` on the
//! corresponding `references/` struct — this module just re-exports them
//! and provides a small home for tests that exercise the generated code
//! against real binary fixtures. Catalogs whose format is too irregular
//! for the derive (multi-section INIs, scripts, dialogues) keep
//! hand-written patchers alongside the generated ones.

mod derived;
mod misc_item;

pub use crate::references::edit_item_db::EditItemPatcher;
pub use crate::references::event_item_db::EventItemPatcher;
pub use crate::references::extra_ref::ExtraRefPatcher;
pub use crate::references::heal_item_db::HealItemPatcher;
pub use crate::references::misc_item_db::MiscItemPatcher;
