use crate::chest_editor;
use crate::db;
use crate::sprite_browser;
use crate::types::{DbOp, MapOp, RefOp, SpriteMode, Tab};
use std::path::PathBuf;

use dispel_core::{
    ChData, Dialog, DialogueText, DrawItem, EditItem, Event, EventItem, EventNpcRef, Extra,
    ExtraRef, HealItem, MagicSpell, Map, MapIni, Message as ScrMessage, MiscItem, Monster,
    MonsterRef, NpcIni, PartyIniNpc, PartyLevelNpc, PartyRef, Quest, Store, WaveIni, WeaponItem,
    NPC,
};

#[derive(Debug, Clone)]
pub enum Message {
    TabSelected(Tab),
    // Shared Game Path
    BrowseSharedGamePath,
    LoadSharedGamePath,
    // Map
    MapOpSelected(MapOp),
    MapInputChanged(String),
    MapOutputChanged(String),
    MapMapPathChanged(String),
    MapBtlPathChanged(String),
    MapGtlPathChanged(String),
    MapSaveSpritesToggled(bool),
    MapDatabaseChanged(String),
    MapMapIdChanged(String),
    MapGtlAtlasChanged(String),
    MapBtlAtlasChanged(String),
    MapAtlasColumnsChanged(String),
    MapGamePathChanged(String),
    // Browse buttons
    BrowseMapInput,
    BrowseMapMapPath,
    BrowseMapBtlPath,
    BrowseMapGtlPath,
    BrowseMapGtlAtlas,
    BrowseMapBtlAtlas,
    BrowseMapGamePath,
    BrowseRefInput,
    BrowseSpriteInput,
    BrowseSoundInput,
    BrowseSoundOutput,
    BrowseExtractorPath,
    FileSelected {
        field: String,
        path: Option<PathBuf>,
    },
    // Ref
    RefOpSelected(RefOp),
    RefInputChanged(String),
    // Database
    DbOpSelected(DbOp),
    // Sprite
    SpriteInputChanged(String),
    SpriteModeSelected(SpriteMode),
    // Sound
    SoundInputChanged(String),
    SoundOutputChanged(String),
    // Global
    ExtractorPathChanged(String),
    Run,
    CommandFinished(Result<String, String>),
    ClearLog,
    // DB Viewer messages
    ViewerDbPathChanged(String),
    ViewerBrowseDb,
    ViewerConnect,
    ViewerTablesLoaded(Result<Vec<String>, String>),
    ViewerSelectTable(String),
    ViewerDataLoaded(Result<db::QueryResult, String>),
    ViewerSearch(String),
    ViewerSortColumn(usize),
    ViewerNextPage,
    ViewerPrevPage,
    ViewerCellClick(usize, usize),
    ViewerCellEdit(String),
    ViewerCellConfirm,
    ViewerCellCancel,
    ViewerCommit,
    ViewerCommitDone(Result<usize, String>),
    ViewerToggleSql,
    ViewerSqlChanged(String),
    ViewerRunSql,
    ViewerExportCsv,
    ViewerCsvSaved(Result<String, String>),
    ViewerRevertEdits,
    // Chest Editor internal
    ChestCatalogLoaded(Result<chest_editor::ItemCatalog, String>),
    // Weapon Editor internal
    WeaponCatalogLoaded(Result<Vec<WeaponItem>, String>),
    // Heal Item Editor internal
    HealItemCatalogLoaded(Result<Vec<HealItem>, String>),
    ChestMapLoaded(Result<Vec<dispel_core::ExtraRef>, String>),
    ChestMapsScanned(Result<Vec<PathBuf>, String>),
    ChestSaved(Result<(), String>),
    // Chest Editor
    ChestOpBrowseGamePath,
    ChestOpBrowseMapFile,
    ChestOpScanMaps,
    ChestOpLoadCatalog,
    ChestOpSelectMap,
    ChestOpSelectMapFromFile(PathBuf),
    ChestOpSelectChest(usize),
    ChestOpFieldChanged(usize, String, String), // (original_index, field_name, new_value)
    ChestOpSave,
    ChestOpAdd,
    ChestOpDelete(usize),
    // Weapon Editor
    WeaponOpBrowseGamePath,
    WeaponOpScanWeapons,
    WeaponOpSelectWeapon(usize),
    WeaponOpFieldChanged(usize, String, String),
    WeaponOpSave,
    // Heal Item Editor
    HealItemOpBrowseGamePath,
    HealItemOpBrowseSpritePath,
    HealItemOpScanItems,
    HealItemOpSelectItem(usize),
    HealItemOpFieldChanged(usize, String, String),
    HealItemOpSave,
    // Misc Item Editor
    MiscItemOpBrowseGamePath,
    MiscItemOpLoadCatalog,
    MiscItemOpScanItems,
    MiscItemOpSelectItem(usize),
    MiscItemOpFieldChanged(usize, String, String),
    MiscItemOpSave,
    MiscItemCatalogLoaded(Result<Vec<MiscItem>, String>),
    // Edit Item Editor
    EditItemOpBrowseGamePath,
    EditItemOpLoadCatalog,
    EditItemOpScanItems,
    EditItemOpSelectItem(usize),
    EditItemOpFieldChanged(usize, String, String),
    EditItemOpSave,
    EditItemCatalogLoaded(Result<Vec<EditItem>, String>),
    // Event Item Editor
    EventItemOpBrowseGamePath,
    EventItemOpLoadCatalog,
    EventItemOpScanItems,
    EventItemOpSelectItem(usize),
    EventItemOpFieldChanged(usize, String, String),
    EventItemOpSave,
    EventItemCatalogLoaded(Result<Vec<EventItem>, String>),
    // Monster Editor
    MonsterOpBrowseGamePath,
    MonsterOpLoadCatalog,
    MonsterOpScanMonsters,
    MonsterOpSelectMonster(usize),
    MonsterOpFieldChanged(usize, String, String),
    MonsterOpSave,
    MonsterCatalogLoaded(Result<Vec<Monster>, String>),
    // NPC Ini Editor
    NpcIniOpBrowseGamePath,
    NpcIniOpLoadCatalog,
    NpcIniOpScanNpcs,
    NpcIniOpSelectNpc(usize),
    NpcIniOpFieldChanged(usize, String, String),
    NpcIniOpSave,
    NpcIniCatalogLoaded(Result<Vec<NpcIni>, String>),
    // Magic Editor
    MagicOpBrowseGamePath,
    MagicOpLoadCatalog,
    MagicOpScanSpells,
    MagicOpSelectSpell(usize),
    MagicOpFieldChanged(usize, String, String),
    MagicOpSave,
    MagicCatalogLoaded(Result<Vec<MagicSpell>, String>),
    // Store Editor
    StoreOpBrowseGamePath,

    StoreOpLoadCatalog,
    StoreOpScanStores,
    StoreOpSelectStore(usize),
    StoreOpFieldChanged(usize, String, String),
    StoreOpSelectProduct(usize),
    StoreOpAddProduct,
    StoreOpRemoveProduct(usize),
    StoreOpProductFieldChanged(usize, String, String),
    StoreOpSave,
    StoreCatalogLoaded(Result<Vec<Store>, String>),
    StoreCatalogWithItemsLoaded(
        Result<
            (
                Option<Vec<WeaponItem>>,
                Option<Vec<HealItem>>,
                Option<Vec<MiscItem>>,
                Option<Vec<EditItem>>,
                Vec<Store>,
            ),
            String,
        >,
    ),
    // Party Ref Editor
    PartyRefOpBrowseGamePath,
    PartyRefOpLoadCatalog,
    PartyRefOpScanParty,
    PartyRefOpSelectMember(usize),
    PartyRefOpFieldChanged(usize, String, String),
    PartyRefOpSave,
    PartyRefCatalogLoaded(Result<Vec<PartyRef>, String>),
    // Party Ini Editor
    PartyIniOpBrowseGamePath,
    PartyIniOpLoadCatalog,
    PartyIniOpScanNpcs,
    PartyIniOpSelectNpc(usize),
    PartyIniOpFieldChanged(usize, String, String),
    PartyIniOpSave,
    PartyIniCatalogLoaded(Result<Vec<PartyIniNpc>, String>),
    // Sprite Browser
    SpriteBrowserOpBrowsePath,
    SpriteBrowserOpScan,
    SpriteBrowserOpSearch(String),
    SpriteBrowserOpSelectSprite(usize),
    SpriteBrowserOpSelectSequence(usize),
    SpriteBrowserOpSelectFrame(usize),
    SpriteBrowserScanned(Result<Vec<sprite_browser::SpriteEntry>, String>),
    // Monster Ref Editor
    MonsterRefOpBrowseFile,
    MonsterRefOpSelectFile(PathBuf),
    MonsterRefOpScanFiles,
    MonsterRefOpFilesScanned(Vec<PathBuf>),
    MonsterRefOpSelectEntry(usize),
    MonsterRefOpFieldChanged(usize, String, String),
    MonsterRefOpSave,
    MonsterRefCatalogLoaded(Result<Vec<MonsterRef>, String>),
    // All Map Ini Editor
    AllMapIniOpBrowseGamePath,
    AllMapIniOpLoadCatalog,
    AllMapIniOpSelectMap(usize),
    AllMapIniOpFieldChanged(usize, String, String),
    AllMapIniOpSave,
    AllMapIniCatalogLoaded(Result<Vec<Map>, String>),
    // Dialog Editor
    DialogOpBrowseGamePath,
    DialogOpBrowseFile,
    DialogOpSelectFile(PathBuf),
    DialogOpLoadCatalog,
    DialogOpSelectDialog(usize),
    DialogOpFieldChanged(usize, String, String),
    DialogOpSave,
    DialogCatalogLoaded(Result<Vec<Dialog>, String>),
    // Dialogue Text Editor
    DialogueTextOpBrowseGamePath,
    DialogueTextOpBrowseFile,
    DialogueTextOpSelectFile(PathBuf),
    DialogueTextOpLoadCatalog,
    DialogueTextOpSelectText(usize),
    DialogueTextOpFieldChanged(usize, String, String),
    DialogueTextOpSave,
    DialogueTextCatalogLoaded(Result<Vec<DialogueText>, String>),
    // Draw Item Editor
    DrawItemOpBrowseGamePath,
    DrawItemOpLoadCatalog,
    DrawItemOpSelectItem(usize),
    DrawItemOpFieldChanged(usize, String, String),
    DrawItemOpSave,
    DrawItemCatalogLoaded(Result<Vec<DrawItem>, String>),
    // Event Ini Editor
    EventIniOpBrowseGamePath,
    EventIniOpLoadCatalog,
    EventIniOpSelectEvent(usize),
    EventIniOpFieldChanged(usize, String, String),
    EventIniOpSave,
    EventIniCatalogLoaded(Result<Vec<Event>, String>),
    // Event Npc Ref Editor
    EventNpcRefOpBrowseGamePath,
    EventNpcRefOpLoadCatalog,
    EventNpcRefOpSelectNpc(usize),
    EventNpcRefOpFieldChanged(usize, String, String),
    EventNpcRefOpSave,
    EventNpcRefCatalogLoaded(Result<Vec<EventNpcRef>, String>),
    // Extra Ini Editor
    ExtraIniOpBrowseGamePath,
    ExtraIniOpLoadCatalog,
    ExtraIniOpSelectExtra(usize),
    ExtraIniOpFieldChanged(usize, String, String),
    ExtraIniOpSave,
    ExtraIniCatalogLoaded(Result<Vec<Extra>, String>),
    // Extra Ref Editor
    ExtraRefOpBrowseGamePath,
    ExtraRefOpBrowseMapFile,
    ExtraRefOpSelectMapFile(PathBuf),
    ExtraRefOpLoadCatalog,
    ExtraRefOpSelectItem(usize),
    ExtraRefOpFieldChanged(usize, String, String),
    ExtraRefOpSave,
    ExtraRefCatalogLoaded(Result<Vec<ExtraRef>, String>),
    // Map Ini Editor
    MapIniOpBrowseGamePath,
    MapIniOpLoadCatalog,
    MapIniOpSelectMap(usize),
    MapIniOpFieldChanged(usize, String, String),
    MapIniOpSave,
    MapIniCatalogLoaded(Result<Vec<MapIni>, String>),
    // Message Scr Editor
    MessageScrOpBrowseGamePath,
    MessageScrOpLoadCatalog,
    MessageScrOpSelectMessage(usize),
    MessageScrOpFieldChanged(usize, String, String),
    MessageScrOpSave,
    MessageScrCatalogLoaded(Result<Vec<ScrMessage>, String>),
    // Npc Ref Editor
    NpcRefOpBrowseGamePath,
    NpcRefOpBrowseMapFile,
    NpcRefOpSelectMapFile(PathBuf),
    NpcRefOpLoadCatalog,
    NpcRefOpSelectNpc(usize),
    NpcRefOpFieldChanged(usize, String, String),
    NpcRefOpSave,
    NpcRefCatalogLoaded(Result<Vec<NPC>, String>),
    // Party Level Db Editor
    PartyLevelDbOpBrowseGamePath,
    PartyLevelDbOpLoadCatalog,
    PartyLevelDbOpSelectNpc(usize),
    PartyLevelDbOpSelectRecord(usize),
    PartyLevelDbOpFieldChanged(String, String),
    PartyLevelDbOpSave,
    PartyLevelDbCatalogLoaded(Result<Vec<PartyLevelNpc>, String>),
    // Quest Scr Editor
    QuestScrOpBrowseGamePath,
    QuestScrOpLoadCatalog,
    QuestScrOpSelectQuest(usize),
    QuestScrOpFieldChanged(usize, String, String),
    QuestScrOpSave,
    QuestScrCatalogLoaded(Result<Vec<Quest>, String>),
    // Wave Ini Editor
    WaveIniOpBrowseGamePath,
    WaveIniOpLoadCatalog,
    WaveIniOpSelectWave(usize),
    WaveIniOpFieldChanged(usize, String, String),
    WaveIniOpSave,
    WaveIniCatalogLoaded(Result<Vec<WaveIni>, String>),
    // ChData Editor
    ChDataOpBrowseGamePath,
    ChDataOpLoadCatalog,
    ChDataOpFieldChanged(String, String),
    ChDataOpSave,
    ChDataCatalogLoaded(Result<Vec<ChData>, String>),
}
