use crate::chest_editor;
use crate::db;
use crate::types::{DbOp, MapOp, RefOp, SpriteMode, Tab};
use std::path::PathBuf;

use dispel_core::{
    EditItem, EventItem, HealItem, MagicSpell, MiscItem, Monster, NpcIni, PartyIniNpc, PartyRef,
    Store, WeaponItem,
};

#[derive(Debug, Clone)]
pub enum Message {
    TabSelected(Tab),
    // Shared Game Path
    BrowseSharedGamePath,
    LoadSharedGamePath,
    // Map
    MapOpSelected(MapOp),
    MapInputChanged(String),
    MapOutputChanged(String),
    MapMapPathChanged(String),
    MapBtlPathChanged(String),
    MapGtlPathChanged(String),
    MapSaveSpritesToggled(bool),
    MapDatabaseChanged(String),
    MapMapIdChanged(String),
    MapGtlAtlasChanged(String),
    MapBtlAtlasChanged(String),
    MapAtlasColumnsChanged(String),
    MapGamePathChanged(String),
    // Browse buttons
    BrowseMapInput,
    BrowseMapMapPath,
    BrowseMapBtlPath,
    BrowseMapGtlPath,
    BrowseMapGtlAtlas,
    BrowseMapBtlAtlas,
    BrowseMapGamePath,
    BrowseRefInput,
    BrowseSpriteInput,
    BrowseSoundInput,
    BrowseSoundOutput,
    BrowseExtractorPath,
    FileSelected {
        field: String,
        path: Option<PathBuf>,
    },
    // Ref
    RefOpSelected(RefOp),
    RefInputChanged(String),
    // Database
    DbOpSelected(DbOp),
    // Sprite
    SpriteInputChanged(String),
    SpriteModeSelected(SpriteMode),
    // Sound
    SoundInputChanged(String),
    SoundOutputChanged(String),
    // Global
    ExtractorPathChanged(String),
    Run,
    CommandFinished(Result<String, String>),
    ClearLog,
    // DB Viewer messages
    ViewerDbPathChanged(String),
    ViewerBrowseDb,
    ViewerConnect,
    ViewerTablesLoaded(Result<Vec<String>, String>),
    ViewerSelectTable(String),
    ViewerDataLoaded(Result<db::QueryResult, String>),
    ViewerSearch(String),
    ViewerSortColumn(usize),
    ViewerNextPage,
    ViewerPrevPage,
    ViewerCellClick(usize, usize),
    ViewerCellEdit(String),
    ViewerCellConfirm,
    ViewerCellCancel,
    ViewerCommit,
    ViewerCommitDone(Result<usize, String>),
    ViewerToggleSql,
    ViewerSqlChanged(String),
    ViewerRunSql,
    ViewerExportCsv,
    ViewerCsvSaved(Result<String, String>),
    ViewerRevertEdits,
    // Chest Editor internal
    ChestCatalogLoaded(Result<chest_editor::ItemCatalog, String>),
    // Weapon Editor internal
    WeaponCatalogLoaded(Result<Vec<WeaponItem>, String>),
    // Heal Item Editor internal
    HealItemCatalogLoaded(Result<Vec<HealItem>, String>),
    ChestMapLoaded(Result<Vec<dispel_core::ExtraRef>, String>),
    ChestMapsScanned(Result<Vec<PathBuf>, String>),
    ChestSaved(Result<(), String>),
    // Chest Editor
    ChestOpBrowseGamePath,
    ChestOpBrowseMapFile,
    ChestOpScanMaps,
    ChestOpLoadCatalog,
    ChestOpSelectMap,
    ChestOpSelectMapFromFile(PathBuf),
    ChestOpSelectChest(usize),
    ChestOpFieldChanged(usize, String, String), // (original_index, field_name, new_value)
    ChestOpSave,
    ChestOpAdd,
    ChestOpDelete(usize),
    // Weapon Editor
    WeaponOpBrowseGamePath,
    WeaponOpScanWeapons,
    WeaponOpSelectWeapon(usize),
    WeaponOpFieldChanged(usize, String, String),
    WeaponOpSave,
    // Heal Item Editor
    HealItemOpBrowseGamePath,
    HealItemOpBrowseSpritePath,
    HealItemOpLoadCatalog,
    HealItemOpScanItems,
    HealItemOpSelectItem(usize),
    HealItemOpFieldChanged(usize, String, String),
    HealItemOpSave,
    // Misc Item Editor
    MiscItemOpBrowseGamePath,
    MiscItemOpLoadCatalog,
    MiscItemOpScanItems,
    MiscItemOpSelectItem(usize),
    MiscItemOpFieldChanged(usize, String, String),
    MiscItemOpSave,
    MiscItemCatalogLoaded(Result<Vec<MiscItem>, String>),
    // Edit Item Editor
    EditItemOpBrowseGamePath,
    EditItemOpLoadCatalog,
    EditItemOpScanItems,
    EditItemOpSelectItem(usize),
    EditItemOpFieldChanged(usize, String, String),
    EditItemOpSave,
    EditItemCatalogLoaded(Result<Vec<EditItem>, String>),
    // Event Item Editor
    EventItemOpBrowseGamePath,
    EventItemOpLoadCatalog,
    EventItemOpScanItems,
    EventItemOpSelectItem(usize),
    EventItemOpFieldChanged(usize, String, String),
    EventItemOpSave,
    EventItemCatalogLoaded(Result<Vec<EventItem>, String>),
    // Monster Editor
    MonsterOpBrowseGamePath,
    MonsterOpLoadCatalog,
    MonsterOpScanMonsters,
    MonsterOpSelectMonster(usize),
    MonsterOpFieldChanged(usize, String, String),
    MonsterOpSave,
    MonsterCatalogLoaded(Result<Vec<Monster>, String>),
    // NPC Ini Editor
    NpcIniOpBrowseGamePath,
    NpcIniOpLoadCatalog,
    NpcIniOpScanNpcs,
    NpcIniOpSelectNpc(usize),
    NpcIniOpFieldChanged(usize, String, String),
    NpcIniOpSave,
    NpcIniCatalogLoaded(Result<Vec<NpcIni>, String>),
    // Magic Editor
    MagicOpBrowseGamePath,
    MagicOpLoadCatalog,
    MagicOpScanSpells,
    MagicOpSelectSpell(usize),
    MagicOpFieldChanged(usize, String, String),
    MagicOpSave,
    MagicCatalogLoaded(Result<Vec<MagicSpell>, String>),
    // Store Editor
    StoreOpBrowseGamePath,

    StoreOpLoadCatalog,
    StoreOpScanStores,
    StoreOpSelectStore(usize),
    StoreOpFieldChanged(usize, String, String),
    StoreOpSelectProduct(usize),
    StoreOpAddProduct,
    StoreOpRemoveProduct(usize),
    StoreOpProductFieldChanged(usize, String, String),
    StoreOpSave,
    StoreCatalogLoaded(Result<Vec<Store>, String>),
    StoreCatalogWithItemsLoaded(
        Result<
            (
                Option<Vec<WeaponItem>>,
                Option<Vec<HealItem>>,
                Option<Vec<MiscItem>>,
                Option<Vec<EditItem>>,
                Vec<Store>,
            ),
            String,
        >,
    ),
    // Party Ref Editor
    PartyRefOpBrowseGamePath,
    PartyRefOpLoadCatalog,
    PartyRefOpScanParty,
    PartyRefOpSelectMember(usize),
    PartyRefOpFieldChanged(usize, String, String),
    PartyRefOpSave,
    PartyRefCatalogLoaded(Result<Vec<PartyRef>, String>),
    // Party Ini Editor
    PartyIniOpBrowseGamePath,
    PartyIniOpLoadCatalog,
    PartyIniOpScanNpcs,
    PartyIniOpSelectNpc(usize),
    PartyIniOpFieldChanged(usize, String, String),
    PartyIniOpSave,
    PartyIniCatalogLoaded(Result<Vec<PartyIniNpc>, String>),
}
