pub mod detect;
pub(crate) mod entries;
pub mod types;

// Re-export public API
pub use detect::{FILE_TYPES, detect, format_type_list, get_by_key, suggest_similar_keys};
pub use types::{DetectResult, FileType};

/// Canonical field definitions per file type key.
/// Single source of truth for schema generation and template generation.
pub fn get_type_fields(key: &str) -> Vec<String> {
    match key {
        "weapons" => vec![
            "id",
            "name",
            "description",
            "base_price",
            "health_points",
            "mana_points",
            "strength",
            "agility",
            "wisdom",
            "constitution",
            "to_dodge",
            "to_hit",
            "attack",
            "defense",
            "magical_strength",
            "durability",
            "req_strength",
            "req_agility",
            "req_wisdom",
        ],
        "monsters" => vec![
            "id",
            "name",
            "ai_type",
            "health_points_min",
            "health_points_max",
            "mana_points_min",
            "mana_points_max",
            "offense_min",
            "offense_max",
            "defense_min",
            "defense_max",
            "to_hit_min",
            "to_hit_max",
            "to_dodge_min",
            "to_dodge_max",
            "magic_attack_min",
            "magic_attack_max",
            "attack_speed",
            "walk_speed",
            "boldness",
            "magic_level",
            "known_spell_slot1",
            "known_spell_slot2",
            "known_spell_slot3",
            "special_attack",
            "special_attack_chance",
            "special_attack_duration",
            "exp_gain_min",
            "exp_gain_max",
            "gold_drop_min",
            "gold_drop_max",
            "detection_sight_size",
            "distance_range_size",
            "is_oversize",
            "is_undead",
            "has_blood",
        ],
        "all_maps" => vec![
            "id",
            "map_filename",
            "map_name",
            "pgp_filename",
            "dlg_filename",
            "lighting",
        ],
        "map_ini" => vec![
            "id",
            "start_x",
            "start_y",
            "start_dir",
            "monsters",
            "npcs",
            "extras",
            "camera_event",
            "cd_track",
        ],
        "monster_ini" => vec![
            "id",
            "name",
            "sprite_filename",
            "attack",
            "hit",
            "death",
            "walking",
            "casting_magic",
        ],
        "npc_ini" => vec![
            "id",
            "name",
            "sprite_filename",
            "attack",
            "hit",
            "death",
            "walking",
            "casting_magic",
        ],
        "quest" => vec!["id", "type_id", "title", "description"],
        "message" => vec!["id", "text"],
        "magic" => vec![
            "id",
            "name",
            "description",
            "mp_cost",
            "spell_level",
            "school",
            "target_type",
            "flag",
            "constant",
            "effect",
        ],
        "store" => vec![
            "id",
            "name",
            "product_type",
            "product_id",
            "price",
            "haggle_min",
            "haggle_max",
            "dialog_id",
        ],
        _ => vec!["id"],
    }
    .into_iter()
    .map(String::from)
    .collect()
}
