name: Test
on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_TOOLCHAIN: stable

jobs:
  compile:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false

      - name: Install Rust
        uses: dimspell/dispel-extractor/.github/actions/setup-rust@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: clippy, rustfmt
          target: aarch64-unknown-linux-musl, x86_64-pc-windows-msvc

      - name: Cache Cargo dependencies
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        id: cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
          key: test-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}-compile
          restore-keys: |
            test-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}-compile

      - name: Build project
        run: cargo build
